#!/bin/bash

module load RoseTTAFold
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp0.fasta e2e_out_vp5_p0
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp1.fasta e2e_out_vp5_p1
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp2.fasta e2e_out_vp5_p2
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp3.fasta e2e_out_vp5_p3
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp4.fasta e2e_out_vp5_p4
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp5.fasta e2e_out_vp5_p5
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp6.fasta e2e_out_vp5_p6
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp7.fasta e2e_out_vp5_p7
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp8.fasta e2e_out_vp5_p8
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp9.fasta e2e_out_vp5_p9
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp10.fasta e2e_out_vp5_p10
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp11.fasta e2e_out_vp5_p11
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp12.fasta e2e_out_vp5_p12
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp13.fasta e2e_out_vp5_p13
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp14.fasta e2e_out_vp5_p14
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp15.fasta e2e_out_vp5_p15
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp16.fasta e2e_out_vp5_p16
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp17.fasta e2e_out_vp5_p17
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp18.fasta e2e_out_vp5_p18
run_e2e_ver_part1.sh rosettafold/vp5_perp/perp19.fasta e2e_out_vp5_p19




run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp0.fasta pyrosetta_out_vp5_p0
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp1.fasta pyrosetta_out_vp5_p1
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp2.fasta pyrosetta_out_vp5_p2
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp3.fasta pyrosetta_out_vp5_p3
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp4.fasta pyrosetta_out_vp5_p4
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp5.fasta pyrosetta_out_vp5_p5
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp6.fasta pyrosetta_out_vp5_p6
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp7.fasta pyrosetta_out_vp5_p7
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp8.fasta pyrosetta_out_vp5_p8
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp9.fasta pyrosetta_out_vp5_p9
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp10.fasta pyrosetta_out_vp5_p10
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp11.fasta pyrosetta_out_vp5_p11
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp12.fasta pyrosetta_out_vp5_p12
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp13.fasta pyrosetta_out_vp5_p13
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp14.fasta pyrosetta_out_vp5_p14
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp15.fasta pyrosetta_out_vp5_p15
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp16.fasta pyrosetta_out_vp5_p16
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp17.fasta pyrosetta_out_vp5_p17
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp18.fasta pyrosetta_out_vp5_p18
run_pyrosetta_ver_part1.sh rosettafold/vp5_perp/perp19.fasta pyrosetta_out_vp5_p19
